[[pages]]
path = "Home.py"
name = "ğŸ  Home"
icon = "house"

[[pages]]
path = "pages/carbonfootprint.py"
name = "ğŸŒ± Carbon Footprint"
icon = "leaf"

[[pages]]
path = "pages/dashboard.py"
name = "ğŸ“Š Dashboard"
icon = "bar-chart"

[[pages]]
path = "pages/aboutus.py"
name = "â„¹ï¸ About Us"
icon = "info"
